### ISSUE TITLE
Tableau.pkg recipe can't find version info

### ISSUE THREAD

**Issue by Chalcahuite** [autopkg/gmarnin-recipes#7]
When running the .pkg recipe or a downstream .jss recipe, recipe fails when trying to determine version info, the app name differs now. Mirroring changes from the munki recipe to the pkg recipe resolves for version info. See pull request.

**Comment by gmarnin** [comment]
Fixed with https://github.com/autopkg/gmarnin-recipes/commit/ac8c3929d572b81968429a02ee82b7bd41094687
